<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>PortfolioSaver.Screensaver.Program</StartupObject>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>..\PortfolioSaver.Shared\Assets\Branding\dnppv-icon-rev-3.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PortfolioSaver.Presentation\PortfolioSaver.Presentation.csproj" />
    <ProjectReference Include="..\PortfolioSaver.Shared\PortfolioSaver.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

